# Copyright (c) 2025 Archie Bradby
# All rights reserved.

def maze(prime):
    prime.moveForward(60)
    prime.turnRight()
    prime.moveForward(43)
    prime.turnRight()
    prime.moveForward(40)
    prime.turnLeft()
    prime.moveForward(80)
    prime.turnLeft()
    prime.moveForward(40)
    prime.turnLeft()
    prime.moveForward(40)
    prime.turnRight()
    prime.moveForward(40)
    prime.turnLeft()
    prime.moveForward(80)
    prime.turnRight()
    prime.moveForward(40)
    prime.turnRight()
    prime.turnRight()
    prime.moveForward(40)
    prime.turnLeft()
    prime.moveForward(40)
    prime.turnLeft()
    prime.moveForward(40)
    prime.turnRight()
    prime.moveForward(80)
    prime.turnRight()
    prime.moveForward(40)
    prime.turnLeft()
    prime.moveForward(10)